language: cpp
compiler:
  - gcc
  - clang
env:
  - GAP_CONFIGURE_FLAGS="" PKG_CONFIGURE_FLAGS=""
  - GAP_CONFIGURE_FLAGS="ABI=32 --host=i686-linux-gnumake" PKG_CONFIGURE_FLAGS="CFLAGS=-m32 CXXFLAGS=-m32 LDFLAGS=-m32 --host=i686-linux-gnu"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - g++-5-multilib
    - clang-3.6
before_script:
  - echo "deb http://us.archive.ubuntu.com/ubuntu/ vivid main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install libgmp-dev
  - sudo apt-get install libgmp-dev:i386
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi
script:
  - scripts/travis-build.sh
  - scripts/travis-test.sh
