dist:
  trusty

language:
  cpp

compiler:
  gcc

env:
  global:
    - GAPDOC=GAPDoc-1.6
    - COVDIR=coverage
    - LIBSEMI=v0.5.2
    - g++=g++-5
    - gcc=gcc-5

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5-multilib

# Matrix
#                    | GAP: master  | GAP: stable-4.9 | GAP: required |
#--------------------+--------------+-----------------+---------------+
# packages:   newest | 64- & 32-bit |               - |             - |
# packages: required |   (coverage) |               - |             - |

# Plus: linting, and code coverage

matrix:
  include:
    - env:
      - SUITE=lint
      addons:
        apt_packages:
      sudo:
        false

    - env:
      - SUITE=test
      - ABI=64
      - GAP=master
      - PACKAGES=newest
      sudo:
        required

    - env:
      - SUITE=test
      - ABI=64
      - GAP=master # change to required once 4.9 is released
      - PACKAGES=required
      sudo:
        required

    - env:
      - SUITE=test
      - ABI=32
      - GAP=master
      - PACKAGES=newest
      sudo:
        required

    - env:
      - SUITE=coverage
      - ABI=64
      - GAP=master
      - PACKAGES=required
      - THRESHOLD=95
      sudo:
        required

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$ABI" == "32" ]; then export GAP_FLAGS="ABI=32 --host=i686-linux-gnu"; fi
  - if [ "$ABI" == "32" ]; then export PKG_FLAGS="CFLAGS=-m32 CXXFLAGS=-m32 LDFLAGS=-m32 LOPTS=-m32 --host=i686-linux-gnu"; fi

before_script:
  - export GAPROOT="$HOME/gap"
  - if [ ! "$SUITE" == "lint" ]; then echo "deb http://us.archive.ubuntu.com/ubuntu/ vivid main" | sudo tee -a /etc/apt/sources.list; fi;
  - if [ ! "$SUITE" == "lint" ]; then sudo apt-get update -qq; fi;
  - if [ ! "$SUITE" == "lint" ]; then sudo apt-get install libgmp-dev; fi;
  - if [ ! "$SUITE" == "lint" ]; then sudo apt-get install libgmp-dev:i386; fi;
  - if [ ! "$SUITE" == "lint" ]; then sudo apt-get install --only-upgrade autoconf; fi;
  - scripts/travis-build-dependencies.sh

script:
  - scripts/travis-build-semigroups.sh && scripts/travis-test.sh
