name: Semigroups
version: 2.7.5
date: 19/04/2016
description: 

authors:
    - name: J. D. Mitchell
      url: http://www-groups.mcs.st-andrews.ac.uk/~jamesm/
    - name: Manuel Delgado
      url: http://cmup.fc.up.pt/cmup/mdelgado/
    - name: J. East
      url: http://www.uws.edu.au/staff_profiles/uws_profiles/doctor_james_east
    - name: Attila Egri-Nagy
      url: http://www.egri-nagy.hu
    - name: J. Jonusas
      url: mailto:jj252@st-and.ac.uk
    - name: Markus Pfeiffer
      url: http://www.morphism.de/~markusp/
    - name: B. Steinberg
      url: http://www.sci.ccny.cuny.edu/~benjamin/
    - name: J. Smith
      url: http://math.sci.ccny.cuny.edu/people?name=Jhevon_Smith
    - name: M. Torpey
      url: mailto:mct25@st-and.ac.uk
    - name: W. Wilson
      url: http://wilf.me

maintainers:
    - name: J. D. Mitchell
      url: http://www-groups.mcs.st-andrews.ac.uk/~jamesm/

GAP: ">=4.8.3"

needed-pkgs:
    - name: "orb"
      version: ">=4.7.3"
      url: "https://gap-packages.github.io/orb"
    - name: "io"
      version: ">=4.4.4"
      url: "http://gap-packages.github.io/io/"

suggested-pkgs:
    - name: "gapdoc"
      version: ">=1.5.1"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "grape"
      version: ">=4.5"
      url: "http://www.maths.qmul.ac.uk/~leonard/grape/"
    - name: "genss"
      version: ">=1.5"
      url: "http://gap-system.github.io/genss/"

www: https://gap-packages.github.io/Semigroups
readme: https://gap-packages.github.io/Semigroups/README
packageinfo: https://gap-packages.github.io/Semigroups/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/Semigroups/releases/download/v2.7.5/semigroups-2.7.5.tar.gz

abstract: <p>The <strong class="pkg">Semigroups</strong> package is a <strong class="pkg">GAP</strong> package containing methods for semigroups, monoids, and inverse semigroups, principally of transformations, partial permutations, bipartitions, subsemigroups of regular Rees 0-matrix semigroups, free inverse semigroups, free bands, and semigroups of matrices over finite fields.</p> <p><strong class="pkg">Semigroups</strong> contains more efficient methods than those available in the <strong class="pkg">GAP</strong> library (and in many cases more efficient than any other software) for creating semigroups, monoids, and inverse semigroup, calculating their Green's structure, ideals, size, elements, group of units, small generating sets, testing membership, finding the inverses of a regular element, factorizing elements over the generators, and many more. It is also possible to test if a semigroup satisfies a particular property, such as if it is regular, simple, inverse, completely regular, and a variety of further properties.</p> <p>There are methods for finding congruences of certain types of semigroups, the normalizer of a semigroup in a permutation group, the maximal subsemigroups of a finite semigroup, and smaller degree partial permutation representations of inverse semigroups. There are functions for producing pictures of the Green's structure of a semigroup, and for drawing bipartitions.</p>

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
