name: "GAP"
on:
  workflow_dispatch:
  pull_request:
  push:
  schedule:
    # Every day at 3:15 AM UTC
    - cron: '15 3 * * *'

jobs:
 
  test-cygwin:
    name: "cygwin64 / GAP master"
    runs-on: windows-latest
    if: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) }}
    env:
      CHERE_INVOKING: 1
    steps:
      - uses: actions/checkout@v2
      - uses: gap-actions/setup-cygwin@v1
      - uses: gap-actions/setup-gap@cygwin-v2
        with:
          GAP_PKGS_TO_BUILD: "digraphs io orb datastructures profiling"
      - uses: gap-actions/build-pkg@cygwin-v1
      - uses: gap-actions/run-pkg-tests@cygwin-v2
        with:
          GAP_TESTFILE: "tst/teststandard.g"
      - uses: gap-actions/process-coverage@cygwin-v2
      - uses: codecov/codecov-action@v2
